# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
        - python: 2.7
          env: TOX_ENV=py27
        - python: 3.5
          env: TOX_ENV=py35

script:
    - tox -e $TOX_ENV
    - flake8 *.py
install: pip install flake8 tox
